=== gabrielv69/WebApp-Practices/7_xml/musicos_clasicos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Musicos (epocas,musico*)>
    <!ELEMENT epocas (epoca*)>
        <!ELEMENT epoca (#PCDATA)>
            <!ATTLIST epoca id ID #REQUIRED>
        <!ELEMENT musico (nombre,apellido,obras,localizacion)>
                <!ATTLIST musico epocahistoria IDREF #IMPLIED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT obras (obra+)>
                <!ELEMENT obra (#PCDATA)>
                    <!ATTLIST obra movimientos CDATA "1">
            <!ELEMENT localizacion (pais,ciudad)>
                <!ELEMENT pais (#PCDATA)>
                <!ELEMENT ciudad (#PCDATA)>

=== gabrielv69/WebApp-Practices/7_xml/musicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Musicos SYSTEM "musicos_clasicos.dtd">
<Musicos>
	<epocas>
		<epoca id= "BR"> BARROCO</epoca>
		<epoca id= "CL"> CLASICISMO</epoca>
	</epocas>
	<musico epocahistoria = "BR">
		<nombre>Antonio</nombre>
		<apellido>Vivaldi</apellido>
		<obras>
			<obra movimientos="4">Las Cuatro Estaciones</obra>
			<obra movimientos="4">Gloria</obra>
		</obras>
		<localizacion>
			<pais>Italia</pais>
			<ciudad>Venecia</ciudad>
		</localizacion>
	</musico>
	<musico epocahistoria = "CL">
		<nombre>Nicolo</nombre>
		<apellido>Paganini</apellido>
		<obras>
			<obra movimientos="4">Campanella</obra>
			<obra movimientos="4">24 caprichos</obra>
		</obras>
		<localizacion>
			<pais>Italia</pais>
			<ciudad>GÃ©nova</ciudad>
		</localizacion>
	</musico>
</Musicos>
